[custom]
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！


;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/ProxyLite.list

ruleset=🔰 Money,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/Money/Moomoo.list
ruleset=🔰 Money,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/Money/Futubull.list
ruleset=🔰 Money,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/Money/uSmart.list
ruleset=🔰 Money,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/Money/Wise.list

ruleset=🤖 AI,https://raw.githubusercontent.com/zsgzzzf/Config/refs/heads/main/Clash/AI.list


ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=📢 GoogleFCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=👨🏿‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🌐 其他地区`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT


custom_proxy_group=📹 YouTube`select`[]🇺🇸 美国节点`[]🔯 美国故转`[]🚀 节点选择`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🤖 AI`select`[]🔯 加坡故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🐸 手动切换
custom_proxy_group=🔰 Money`select`[]🔯 加坡故转`[]🔯 香港故转`[]🐸 手动切换
custom_proxy_group=🐬 OneDrive`select`[]DIRECT`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🪟 Microsoft`select`[]DIRECT`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🐸 手动切换
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=📢 GoogleFCM`select`[]DIRECT`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🐸 手动切换
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]DIRECT`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇹🇳 台湾节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
;custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
;custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换

custom_proxy_group=🐸 手动切换`select`.*
;custom_proxy_group=🏡 家宽节点`select`(家宽|家庭)
custom_proxy_group=🛩️ 高速节点`select`(?=.*(香港|日本|新加坡|台湾|韩国))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$
;custom_proxy_group=🕊️ 便宜节点`select`(?=.*(0.5|0.5倍|0.5x))
custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港|HK|Hong Kong|HongKong))^((?!(US|家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|JP|Japan))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇸🇬 加坡节点`select`(?=.*(新加坡|SG|Singapore))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇹🇳 台湾节点`select`(?=.*(台湾|台|TW|Taiwan))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇰🇷 韩国节点`select`(?=.*(韩国|韩|KR|Korea))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇺🇸 美国节点`select`(美|US|morverthink)
custom_proxy_group=🌐 其他地区`select`(^(?!.*(香港|HK|Hong Kong|HongKong|日本|JP|Japan|新加坡|坡|狮城|SG|Singapore|台湾|台|TW|Taiwan|韩国|韩|KR|Korea|美|US|morverthink)).*)
custom_proxy_group=🔯 香港故转`fallback`(?=.*(香港|HK|Hong Kong|HongKong))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 日本故转`fallback`(?=.*(日本|JP|Japan))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 加坡故转`fallback`(?=.*(新加坡|SG|Singapore))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 美国故转`fallback`(?=.*(美|US|morverthink))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=⭐ 香港故转`fallback`!!GROUPID=!0!!(香港|HK|Hong Kong|HongKong)(?!.*(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=⭐ 日本故转`fallback`!!GROUPID=!0!!(日本|JP|Japan)(?!.*(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=⭐ 加坡故转`fallback`!!GROUPID=!0!!(新加坡|坡|SG|Singapore)(?!.*(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=⭐ 美国故转`fallback`!!GROUPID=!0!!(美|US|United States)(?!.*(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🍃 香港均衡`load-balance`(?=.*(香港|HK|Hong Kong|HongKong))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

;custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)

;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true

